const adjectives = [
  "slutty",
  "slimy",
  "smelly",
  "useless",
  "ugly",
  "snooty",
  "bumpy",
  "stupid",
  "pompous",
  "communist",
  "brainless",
  "booger",
  "high flying",
  "son of a",
  "blue ball",
  "9 stroked",
  "teasing",
  "stout",
  "creepy",
  "annoying",
  "obnoxious",
  "constipated",
  "artificial",
  "aged",
  "gross",
  "white trash",
  "psycho",
  "elitist",
  "idiotic",
  "brown nosed",
  "jackalope",
  "spongy",
  "attention seeking",
  "preppy",
  "shart",
  "insecure",
  "butterface",
  "tone deaf",
  "helmet wearing",
  "completely average",
];

const elaborateAdjective = [
  "moist",
  "duck nosed",
  "duck lipped",
  "slut",
  "banana",
  "freak",
  "loser",
  "whore",
  "mistake",
  "dunce cap",
  "beanbag shaped",
  "crap filled",
  "hook nosed",
  "golf brained",
  "turd",
  "sphincter",
  "ass",
  "dog faced",
  "douche",
  "prick",
  "turd",
  "brained",
  "ass hat",
  "bitch",
  "brony-ass",
  "wart faced",
  "boner",
  "ugly-assed",
  "rectum",
  "taint",
  "nut",
  "wad",
  "butt",
  "ball sucking",
];

const noun = [
  "smurf",
  "airhead",
  "ass-kisser",
  "bastard",
  "bimbo",
  "frosted flake",
  "ginger",
  "blonde",
  "chicken",
  "buggar",
  "fetus",
  "middle of the bell curve",
  "clown",
  "Tasha",
  "waffle",
  "sucker",
  "muffin",
  "dingle berry",
  "cum-guzzler",
  "biscuit",
  "degenerate",
  "socket",
  "nerd",
  "gear head",
  "fool",
  "lettuce",
  "truck",
  "mistake",
  "boomer",
  "millennial",
  "gen-z",
  "uni-brow",
  "dragon",
  "captain",
  "hammer",
  "blossom",
  "cock sucker",
  "fucker",
  "hell monkey",
  "unicorn",
  "goblin",
  "witch",
  "mistake of God",
  "potato",
  "wall",
  "pirate",
  "gremlin",
  "boob",
  "secretion",
  "ball sack",
  "champion",
  "school boy",
  "sheeple",
  "corpse",
  "geek",
  "shit hole",
  "tool bag",
  "whore",
  "canoe",
];

function getInsult() {
  let insultAdj = adjectives[getRandomInt(adjectives.length)];
  let insultElaborate =
    elaborateAdjective[getRandomInt(elaborateAdjective.length)];
  let insultNoun = noun[getRandomInt(noun.length)];
  return insultAdj + " " + insultElaborate + " " + insultNoun;
}

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

module.exports = getInsult;
