const adjectives = [
  "Artless",
  "Bawdy",
  "Beslubbering",
  "Bootless",
  "Churlish",
  "Cockered",
  "Clouted",
  "Craven",
  "Currish",
  "Dankish",
  "Dissembling",
  "Droning",
  "Errant",
  "Fawning",
  "Fobbing",
  "Froward",
  "Frothy",
  "Gleeking",
  "Goatish",
  "Gobellied",
  "Imperinent",
  "Infectious",
  "Jarring",
  "Loggerheaded",
  "Lumpish",
  "Mammering",
  "Mangled",
  "Paunchy",
  "Puking",
  "Puny",
  "Qualling",
  "Rank",
  "Reeky",
  "Roguish",
  "Ruttish",
  "Saucy",
  "Spleeny",
  "Spongy",
  "Surly",
  "Tottering",
  "Unmuzzled",
  "Vain",
  "Venomed",
  "Villainous",
  "Warped",
];

const elaborateAdjective = [
  "base-court",
  "bat-fowling",
  "beef-witted",
  "boil-brained",
  "beetle-headed",
  "common-kissing",
  "crook-pated",
  "dismal-dreaming",
  "dizzy-eyed",
  "dog-hearted",
  "dread-bolted",
  "earth-vexing",
  "elf-skinned",
  "fat-kidneyed",
  "fen-sucked",
  "flap-mouthed",
  "fly-bitten",
  "folly-fallen",
  "fool-born",
  "full-gorged",
  "futs-griping",
  "half-faced",
  "hasty-witted",
  "hedge-born",
  "hell-hated",
  "idle-headed",
  "ill-nurtured",
  "knotty-pated",
  "milk-livered",
  "motley-minded",
  "onion-eyed",
  "plume-plucked",
  "pottle-deep",
  "pox-marked",
  "reeling-ripe",
  "rough-hewn",
  "rude-growing",
  "rump-fed",
  "shard-borne",
  "sheep-biting",
  "spur-galled",
  "swag-bellied",
  "tardy-gaited",
  "tickle-brained",
  "toad-spotted",
  "unchin-snouted",
  "weather-bitten",
];

const noun = [
  "apple-john",
  "baggage",
  "barnacle",
  "bladder",
  "boar-pig",
  "bugbear",
  "bum-bailey",
  "canker-blossom",
  "clack-dish",
  "clotpole",
  "coxcomb",
  "death-token",
  "dewberry",
  "flap-dragon",
  "flax-wench",
  "flirt-gill",
  "foot-licker",
  "fustilarian",
  "giglet",
  "gudgeon",
  "haggard",
  "harpy",
  "hedge-pig",
  "horn-beast",
  "hugger-mugger",
  "jolthead",
  "lewdster",
  "lout",
  "maggot-pie",
  "malt-worm",
  "mammet",
  "measle",
  "minnow",
  "miscreant",
  "moldwarp",
  "mumble-news",
  "nut-hook",
  "pigeon-egg",
  "pignut",
  "puttock",
  "pumpion",
  "ratsbane",
  "scut",
  "skainsmate",
  "strumpet",
  "vartlot",
  "vassal",
];

function getInsult() {
  let insultAdj = adjectives[getRandomInt(adjectives.length)];
  let insultElaborate =
    elaborateAdjective[getRandomInt(elaborateAdjective.length)];
  let insultNoun = noun[getRandomInt(noun.length)];
  return insultAdj + " " + insultElaborate + " " + insultNoun;
}

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

module.exports = getInsult;
